trigger: none

schedules:
- cron: "0 22 * * *"
  displayName: 'Shutdown Schedule'
  branches:
    include:
    - main
  always: true
- cron: "0 7 * * *"
  displayName: 'Startup Schedule'
  branches:
    include:
    - main
  always: true

jobs:
- job: Shutdown
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.CronSchedule.DisplayName'], 'Shutdown Schedule'))
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'fb539a3e-caf4-482b-88d7-5af5d494c42e'
      ScriptType: 'InlineScript'
      Inline: 'Stop-AzContainerApp -Name geoserver -ResourceGroupName visor_dipgra -SubscriptionId fb539a3e-caf4-482b-88d7-5af5d494c42e'
      azurePowerShellVersion: 'LatestVersion'

- job: Startup
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.CronSchedule.DisplayName'], 'Startup Schedule'))
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'fb539a3e-caf4-482b-88d7-5af5d494c42e'
      ScriptType: 'InlineScript'
      Inline: 'Start-AzContainerApp -Name geoserver -ResourceGroupName visor_dipgra -SubscriptionId fb539a3e-caf4-482b-88d7-5af5d494c42e'
      azurePowerShellVersion: 'LatestVersion'